version: '3'
services:
  db:
    build:
      context: ./MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prueba
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    container_name: PKpractice_db
    ports:
      - "3306:3306"
    tty: true
  app:
    build:
      context: ./Go
    volumes:
      - "./Go:/go/src/li"
    container_name: PKpractice_app
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - db